<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EventDriven.Messaging\EventDriven.Messaging.csproj" />
    <ProjectReference Include="..\EventDriven.Contracts\EventDriven.Contracts.csproj" />
  </ItemGroup>
</Project>
